"""empty message

Revision ID: 5175492e3846
Revises: 
Create Date: 2026-07-16 14:05:05.037337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5175492e3846'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cats_entries',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('Issue', sa.String(), nullable=True),
    sa.Column('Status', sa.Enum('HEALTHY', 'SICK', 'RECOVERING', 'ADOPTED', name='catstatus'), nullable=True),
    sa.Column('Gender', sa.Enum('MALE', 'FEMALE', name='catgender'), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_cats_entries_ID'), 'cats_entries', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cats_entries_ID'), table_name='cats_entries')
    op.drop_table('cats_entries')
    # ### end Alembic commands ###
